// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: elastico/elastico.proto

package elastico

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IDProof is a proof for identity.
type IDProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	PK            []byte                 `protobuf:"bytes,2,opt,name=PK,proto3" json:"PK,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDProof) Reset() {
	*x = IDProof{}
	mi := &file_elastico_elastico_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDProof) ProtoMessage() {}

func (x *IDProof) ProtoReflect() protoreflect.Message {
	mi := &file_elastico_elastico_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDProof.ProtoReflect.Descriptor instead.
func (*IDProof) Descriptor() ([]byte, []int) {
	return file_elastico_elastico_proto_rawDescGZIP(), []int{0}
}

func (x *IDProof) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *IDProof) GetPK() []byte {
	if x != nil {
		return x.PK
	}
	return nil
}

func (x *IDProof) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_elastico_elastico_proto protoreflect.FileDescriptor

const file_elastico_elastico_proto_rawDesc = "" +
	"\n" +
	"\x17elastico/elastico.proto\x12\belastico\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\aIDProof\x12\x12\n" +
	"\x04Addr\x18\x01 \x01(\tR\x04Addr\x12\x0e\n" +
	"\x02PK\x18\x02 \x01(\fR\x02PK\x12\x14\n" +
	"\x05Nonce\x18\x03 \x01(\fR\x05Nonce2K\n" +
	"\fSetupService\x12;\n" +
	"\x0eReceiveIDProof\x12\x11.elastico.IDProof\x1a\x16.google.protobuf.EmptyB>Z<github.com/hamzaparekh/blockchain-sharding/elastico;elasticob\x06proto3"

var (
	file_elastico_elastico_proto_rawDescOnce sync.Once
	file_elastico_elastico_proto_rawDescData []byte
)

func file_elastico_elastico_proto_rawDescGZIP() []byte {
	file_elastico_elastico_proto_rawDescOnce.Do(func() {
		file_elastico_elastico_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elastico_elastico_proto_rawDesc), len(file_elastico_elastico_proto_rawDesc)))
	})
	return file_elastico_elastico_proto_rawDescData
}

var file_elastico_elastico_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_elastico_elastico_proto_goTypes = []any{
	(*IDProof)(nil),       // 0: elastico.IDProof
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_elastico_elastico_proto_depIdxs = []int32{
	0, // 0: elastico.SetupService.ReceiveIDProof:input_type -> elastico.IDProof
	1, // 1: elastico.SetupService.ReceiveIDProof:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_elastico_elastico_proto_init() }
func file_elastico_elastico_proto_init() {
	if File_elastico_elastico_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elastico_elastico_proto_rawDesc), len(file_elastico_elastico_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elastico_elastico_proto_goTypes,
		DependencyIndexes: file_elastico_elastico_proto_depIdxs,
		MessageInfos:      file_elastico_elastico_proto_msgTypes,
	}.Build()
	File_elastico_elastico_proto = out.File
	file_elastico_elastico_proto_goTypes = nil
	file_elastico_elastico_proto_depIdxs = nil
}
